### ISSUE TITLE
[epic]Fun with operators ^_^

### ISSUE THREAD

**Issue by one-thunder** [one-lightning/java-newbie-exercises#7]
# Purpose.
Understand java operators and how they interact with variables & values.

# References.

To recap **primitive** variables visit [this link](https://www.programiz.com/java-programming/variables-primitive-data-types#variables)

Also to learn more about operators, click [this link](https://www.programiz.com/java-programming/operators)

# Operators part [1]

### 1 ( TV Channels )
* [ ] Define an unitialized variable with name `channelName`
* [ ] Assign it a value of 'Prime TV'
* [ ] Print `channelName` to console
* [ ] Re-assign the value to `Europa TV`
* [ ] Print `channelName` to console
* [ ] Re-assign the value to `Muz TV`
* [ ] Print `channelName` to console
* [ ] Re-assign the value to `"none"`
* [ ] Print `channelName` to console

### 2.1 ( Vroooom )
* [ ] Define an uninitialized variable with name `carSpeed` of type `short`
* [ ] Assign it a value of 0 + 10
* [ ] Print `carSpeed` to console
* [ ] Assign it a value of 10 + 10
* [ ] Print `carSpeed` to console
* [ ] Repeat this steps until the speed will be 40

### 2.2 ( Summoner Greeter )
* [ ] Define an uninitialized variable with name `greetingPrefix` of type `String`
* [ ] Define an uninitialized variable with name `greetingName` of type `String`
* [ ] Define an uninitialized variable with name `greetingSurname` of type `String`
* [ ] Define an uninitialized variable with name `greetingPostfix` of type `String`
* [ ] Define an uninitialized variable with name `greetingDelimiter` of type `String`
* [ ] Define an uninitialized variable with name `greetingMotivator` of type `String`
* [ ] Define an uninitialized variable with name `greetingFinal` of type `String`
* [ ] Assign `greetingPrefix` a value of `Welcome, `
* [ ] Assign `greetingName` a value of `Sheldor`
* [ ] Assign `greetingSurname` a value of `Booker`
* [ ] Assign `greetingPostfix` a value of `. To Summoners Rift!`
* [ ] Assign `greetingDelimiter` a value of `\n----------------------------------\n`
* [ ] Assign `greetingMotivator` a value of `Pick a champion a let's go fight the enemies!!! `
* [ ] Assign `greetingFinal` a value of all previously defined strings. *hint (concatenate strings using `+` symbol)*

### 2.3 ( Bank Debt )
* [ ] Define a variable with name `bankAccountDebt` of type `int` and initialize the value with `-200`
* [ ] Define a variable with name `offshoreSupplyIncome` of type `int` and initialize the value with `32`
* [ ] Re-assign the `bankAccountDebt` variable value to the following formula :  `bankAccountDebt + offshoreSupplyIncome`
* [ ] Print to console
* [ ] Re-assign the `bankAccountDebt` variable value to the following formula :  `bankAccountDebt + offshoreSupplyIncome`
* [ ] Print to console
* [ ] Repeat the steps until `bankAccountDebt` will be positive.

Notes:
* Print format `"Current bank account debt : %bankAccountDebt%"`

### 2.3 ( Temperature )
* [ ] Define a variable with name `temperature` of type `int` and initialize the value with `0`
* [ ] Print to console
* [ ] Define a variable with name `morningTemperature` of type `int` and initialize the value with `12`
* [ ] Define a variable with name `afternoonTemperature` of type `int` and initialize the value with `20`
* [ ] Perform substraction from `temperature` the value of `morningTemperature` *hint (a = a - b)*
* [ ] Print to console
* [ ] Perform addition to `temperature` the value of `afternoonTemperature`
* [ ] Print to console

Notes:
* Print format `"Current temperature :  %temperature%"`

### 2.4 ( ApartmentsSquarePrice )
* [ ] Define a variable with name `apartmentMetersSquare` of type `int` and initialize the value with `1`
* [ ] Define a variable with name `squarePrice` of type `int` and initialize the value with `440`
* [ ] Define a variable with name `finalPrice` of type `int` and initialize the value with `0`
* [ ] Perform multiply operation between `apartmentMetersSquare` and `squarePrice` and assign the value to `finalPrice`
* [ ] Print to console
* [ ] Perform addition operation on `apartmentMetersSquare` with itself to `22`
* [ ] Perform multiply operation between `apartmentMetersSquare` and `squarePrice` and assign the value to `finalPrice`
* [ ] Print to console
* [ ] Perform addition operation on `apartmentMetersSquare` with itself to `64`
* [ ] Perform multiply operation between `apartmentMetersSquare` and `squarePrice` and assign the value to `finalPrice`
* [ ] Print to console

Notes:
* Print format `"Apartment square meters : %apartmentMetersSquare% , at price cost of  :  %finalPrice%"`

### 2.5 ( SimpleDevision )
* [ ] Define a variable with name `aNumber` of type `int` and initialize the value with `98`
* [ ] Define a variable with name `bNumber` of type `int` and initialize the value with `2`
* [ ] Define a variable with name `resultNumber` of type `int` and initialize the value with `0`
* [ ] Perform devision operation between `aNumber` and `bNumber` and assign the value to `resultNumber`
* [ ] Print to console

Notes:
* Print format `"Dividing, %aNumber% / %bNumber% = %resultNumber% is so f**k*** simple :)"`

### 3.1 ( Inverse balance on card )
* [ ] Define a variable with name `cardBalance` of type `int` and initialize the value with `640`
* [ ] Apply `unary minus` operator to variable `cardBalance`
* [ ] Print to console
* [ ] Apply `unary plus` operator to variable `cardBalance`
* [ ] Print to console

Notes:
* Print format `"Available card balance: %cardBalance%."`

### 3.2 ( Baloon height ++ )
* [ ] Define a variable with name `baloonHeight` of type `short` and initialize the value with `0`
* [ ] Apply `increment` operator to variable `baloonHeight`
* [ ] Print to console
* [ ] Apply `increment` operator to variable `baloonHeight`
* [ ] Print to console
* [ ] Repeat steps until `baloonHeight` will be equal to 4
* [ ] Print to console

Notes:
* Print format `"Oh! Baloon is %baloonHeight%"(meters) above the ground!!`

### 3.3 ( Money in my pocket -- )
* [ ] Define a variable with name `pocketMoney` of type `short` and initialize the value with `30`
* [ ] Apply `decrement` operator to variable `pocketMoney`
* [ ] Print to console
* [ ] Apply `decrement` operator to variable `pocketMoney`
* [ ] Print to console
* [ ] Repeat steps until `pocketMoney` will be equal to 26
* [ ] Print to console

Notes:
* Print format `"Here, take one dollar. I still got %pocketMoney%$ left bro!`

### 3.4 ( A small sweet lie )
* [ ] Define a variable with name `isJonAtTheOffice` of type `boolean` and initialize the value with `false`
* [ ] Apply `Logical complement operator` operator to variable `isJonAtTheOffice`
* [ ] Print to console

Notes:
* Print format `"It's %isJonAtTheOffice%, I think I saw him today.`

### 4.1 ( Height quiz ( in centimeters ) )
* [ ] Define a variable with name `jonHeight` of type `int` and initialize the value with `11`
* [ ] Define a variable with name `billHeight` of type `int` and initialize the value with `12`
* [ ] Define a variable with name `lennyHeight` of type `int` and initialize the value with `9`
* [ ] Print to console `Welcome to height quiz! \n`
* [ ] Print to console `Jon ( %jonHeight cm % ) is shorter then Bill ( %billHeight% cm ) ? Answer : %???% ` *hint ( `less then` operator )*
* [ ] Print to console `Bill ( %billHeight cm % ) is equal to Lenny ( %lennyHeight% cm ) ? Answer : %???% ` *hint ( `equal to` operator )*
* [ ] Print to console `Lenny ( %lennyHeight cm % ) is shorter then Jon ( %jonHeight% cm ) ? Answer : %???% ` *hint ( `less then` operator )*

### 4.2 ( Facebook likes quiz )
* [ ] Define a variable with name `jonPhotoLikes` of type `int` and initialize the value with `23`
* [ ] Define a variable with name `billPhotoLikes` of type `int` and initialize the value with `97`
* [ ] Define a variable with name `lennyPhotoLikes` of type `int` and initialize the value with `8`
* [ ] Print to console `Welcome to Facebook likes quiz! \n`
* [ ] Print to console `Jon's ( %jonPhotoLikes% ) are higher then Bill's ( %billPhotoLikes% ) ? Answer : %???% ` *hint ( `greater than` operator )*
* [ ] Print to console `Bill's ( %billPhotoLikes% ) are less then Lenny's ( %lennyPhotoLikes% ) ? Answer : %???% ` *hint ( `less than` operator )*
* [ ] Print to console `Lenny's ( %lennyPhotoLikes% ) are equal to then Jon's ( %jonPhotoLikes% ) ? Answer : %???% ` *hint ( `equal to` operator )*

##Logical Operators

### 5.1 ( RockConcert )
* [ ] Define a variable with name `hasJonTicketPass` of type `boolean` and initialize the value with `true`
* [ ] Define a variable with name `hasAlfTicketPass` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `hasSaraTicketPass` of type `boolean` and initialize the value with `true`
* [ ] Define a variable with name `canEveryoneEnter` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `canJonAndAlfEnter` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `canJonAndSaraEnter` of type `boolean` and initialize the value with `false`
------
* [ ] Assign to variable `canEveryoneEnter` the result of `conditional-AND` operator between `hasJonTicketPass`, `hasAlfTicketPass`, `hasSaraTicketPass`
* [ ] Assign to variable `canJonAndAlfEnter` the result of `conditional-AND` operator between `hasJonTicketPass`, `hasAlfTicketPass`
* [ ] Assign to variable `canJonAndSaraEnter` the result of `conditional-AND` operator between `hasJonTicketPass`, `hasSaraTicketPass`
------
* [ ] Print to console `Sara: Wow the music is so awesome, I hope nobody forgot their tickets home...?`
* [ ] Print to console `Guys: 'Can we all enter?' \n Guard: My answer is - %canEveryoneEnter%`
* [ ] Print to console `Jon: 'Can I and my bro Alfred enter?' \n Guard: My answer is - %canJonAndAlfEnter%`
* [ ] Print to console `Sara: 'Can I enter with Jon?' \n Guard: My answer is - %canJonAndSaraEnter%`

### 5.2 ( FlowerField )
* [ ] Define a variable with name `hasJonNecessaryPocketMoney` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `hasAlfNecessaryPocketMoney` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `hasSaraNecessaryPocketMoney` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `canEveryoneEnter` of type `boolean` and initialize the value with `false`
------
* [ ] Assign to variable `canEveryoneEnter` the result of `conditional-OR` operator between `hasJonNecessaryPocketMoney`, `hasAlfNecessaryPocketMoney`, `hasSaraNecessaryPocketMoney`
------
* [ ] Print to console `Sara: 'The flower field is so beautifull, but I want to see it from the inside, can we enter?'`
* [ ] Print to console `Guard: 'My answer is :  %canEveryoneEnter%. \nDoes not matter how many of you are here, but if someone donate 20$ you all can enter.'`
* [ ] Print to console `Jon: 'Lets check our pockets...'`
* [ ] Print to console `Alf: 'Whohooo guys I think I have some!'`
------
* [ ] Assign to variable `hasAlfNecessaryPocketMoney` the value of `true`;
* [ ] Assign to variable `canEveryoneEnter` the result of `conditional-OR` operator between `hasJonNecessaryPocketMoney`, `hasAlfNecessaryPocketMoney`, `hasSaraNecessaryPocketMoney`
------
* [ ] Print to console `Jon: 'Can we all enter now, Mr Guard?'`
* [ ] Print to console `Guard: 'My answer is - %canJonAndSaraEnter%. He he.`

### 5.3 ( MSI Championship )
* [ ] Define an unitialized variable with name `hasSKTWon_1Game` of type `boolean`;
* [ ] Define an unitialized variable with name `hasSKTWon_2Game` of type `boolean`;
* [ ] Define an unitialized variable with name `hasSKTWon_3Game` of type `boolean`;
* [ ] Define an unitialized variable with name `hasSKTWon_4Game` of type `boolean`;
* [ ] Define an unitialized variable with name `hasSKTWon_5Game` of type `boolean`;
* [ ] Define an unitialized variable with name `isSKTWinner` of type `boolean`;
------
* [ ] Assign to variable `hasSKTWon_1Game` the value of `true`;
* [ ] Assign to variable `hasSKTWon_2Game` the value of `false`;
* [ ] Assign to variable `hasSKTWon_3Game` the value of `true`;
* [ ] Assign to variable `hasSKTWon_4Game` the value of `false`;
* [ ] Assign to variable `hasSKTWon_5Game` the value of `false`;
* [ ] Assign to variable `isSKTWinner` the result of `conditional-AND` operation between all variables [`hasSKTWon_1Game` ... `hasSKTWon_5Game`]
------
* [ ] Print to console `Is SKT T1 going to finals at this MSI? The answer is: %isSKTWinner%' :((`
* [ ] Print to console `Faker: 'Will revenge at worlds championship!'`

### 5.4 ( Anyways )
* [ ] Define an unitialized variable with name `hasGoodGrades` of type `boolean`;
* [ ] Define an unitialized variable with name `hasFriendsInAdministration` of type `boolean`;
* [ ] Define an unitialized variable with name `hasJonPassedTheExams` of type `boolean`;
* [ ] Define an unitialized variable with name `hasMargoPassedTheExams` of type `boolean`;
* [ ] Define an unitialized variable with name `hasRobPassedTheExams` of type `boolean`;
* [ ] Define an unitialized variable with name `hasCobPassedTheExams` of type `boolean`;
------
* [ ] Assign to variable `hasGoodGrades` the value of `true`;
* [ ] Assign to variable `hasFriendsInAdministration` the value of `false`;
* [ ] Assign to variable `hasJonPassedTheExams` the result of `conditional-OR` between `hasGoodGrades` and `hasFriendsInAdministration`
* [ ] Print to console `hasJonPassedTheExams`
------
* [ ] Assign to variable `hasGoodGrades` the value of `true`;
* [ ] Assign to variable `hasFriendsInAdministration` the value of `true`;
* [ ] Assign to variable `hasMargoPassedTheExams` the result of `conditional-OR` between `hasGoodGrades` and `hasFriendsInAdministration`
* [ ] Print to console `hasMargoPassedTheExams`
------
* [ ] Assign to variable `hasGoodGrades` the value of `false`;
* [ ] Assign to variable `hasFriendsInAdministration` the value of `true`;
* [ ] Assign to variable `hasRobPassedTheExams` the result of `conditional-OR` between `hasGoodGrades` and `hasFriendsInAdministration`
* [ ] Print to console `hasRobPassedTheExams`
------
* [ ] Assign to variable `hasGoodGrades` the value of `false`;
* [ ] Assign to variable `hasFriendsInAdministration` the value of `false`;
* [ ] Assign to variable `hasCobPassedTheExams` the result of `conditional-OR` between `hasGoodGrades` and `hasFriendsInAdministration`
* [ ] Print to console `hasCobPassedTheExams`

Notes:
* Print format `Teacher: Have you passed the exams? Hmm... %variable_name%`

##Instanceof and ternary op.

### 6.1 ( IsOfType )
* [ ] Define a variable with name `sampleBoolean` of type `boolean` and initialize the value with `true`
* [ ] Define a variable with name `sampleString` of type `String` and initialize the value with `"Samplez"`
* [ ] Define a variable with name `sampleByte` of type `byte` and initialize the value with `3`
------
* [ ] Define a variable with name `isBoolean` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `isString` of type `boolean` and initialize the value with `false`
* [ ] Define a variable with name `isByte` of type `boolean` and initialize the value with `false`
------
* [ ] Assign to variable `isBoolean` the result of `instanceof Operator` operator between `sampleBoolean`, `boolean`
* [ ] Print to console `Is 'sampleBoolean' a 'boolean' type? %isBoolean%`
* [ ] Assign to variable `isString` the result of `instanceof Operator` operator between `sampleString`, `String`
* [ ] Print to console `Is 'sampleString' a 'string' type? %isString%`
* [ ] Assign to variable `isByte` the result of `conditional-AND` operator between `sampleByte`, `byte`
* [ ] Print to console `Is 'sampleByte' a 'byte' type? %isByte%`
------
* [ ] Assign to variable `isBoolean` the result of `instanceof Operator` operator between `sampleBoolean`, `String`
* [ ] Print to console `Is 'sampleBoolean' a 'String' type? %isBoolean%`
* [ ] Assign to variable `isString` the result of `instanceof Operator` operator between `sampleString`, `short`
* [ ] Print to console `Is 'sampleString' a 'short' type? %isString%`
* [ ] Assign to variable `isByte` the result of `conditional-AND` operator between `sampleByte`, `boolean`
* [ ] Print to console `Is 'sampleByte' a 'boolean' type? %isByte%`

### 6.2 ( Ternarius )
* [ ] Define a variable with name `years` of type `short` and initialize the value with `0`
* [ ] Define a variable with name `hasPassYearsValidation` of type `boolean` and initialize the value with `false`
------
* [ ] Assign to variable `years` the value of `12`
* [ ] Assign to variable `hasPassYearsValidation` the value of `years >= 18 ? true : false`
* [ ] Print to console `hasPassYearsValidation ? "Too young to enter, please go away : "Welcome to our club"`
------
* [ ] Assign to variable `years` the value of `17`
* [ ] Assign to variable `hasPassYearsValidation` the value of `years >= 18 ? true : false`
* [ ] Print to console `hasPassYearsValidation ? "Too young to enter, please go away : "Welcome to our club"`
------
* [ ] Assign to variable `years` the value of `18`
* [ ] Assign to variable `hasPassYearsValidation` the value of `years >= 18 ? true : false`
* [ ] Print to console `hasPassYearsValidation ? "Too young to enter, please go away : "Welcome to our club"`
------
------
* [ ] Assign to variable `years` the value of `32`
* [ ] Assign to variable `hasPassYearsValidation` the value of `years >= 18 ? true : false`
* [ ] Print to console `hasPassYearsValidation ? "Too young to enter, please go away : "Welcome to our club"`

**Comment by one-thunder** [comment]
All of the items in the epic was done. 
Closing epic
